---
title: "<i class='fa fa-chalkboard-teacher' aria-hidden='true'></i> Kurzusok"
---

* **Számítástechnika 1.**
    * [Hivatkozáskezelők <i class="fab fa-youtube"></i>](https://www.youtube.com/playlist?list=PLnmeQHnHYqv5jzYnu8i2Kh46Ti5g1bVCz){target="_blank"}
    * [Hivatkozáskezelők <i class="far fa-file-pdf"></i>](files/hivatkozaskezelok.pdf){target="_blank"}
* Számítástechnika és könyvtárismeret
* Matematikai alapok
* **Pszichológiai statisztika 1. (paraméteres eljárások)**
    * [Példák próbák végrehajtására <i class="fas fa-external-link-alt"></i>](https://abarik.github.io/stat1_kurzus/){target="_blank"}


* **Az összes kurzushoz**
    * [R könyvek, tutoriálok, blogok, adatbázisok <i class="fas fa-external-link-alt"></i>](https://abarik.github.io/roforrasok/){target="_blank"}
    * [Statisztika könyvek - példa adatbázisok felhasználása <i class="fas fa-external-link-alt"></i>](https://abarik.github.io/statkonyvek/){target="_blank"}
    * [R a gyakorlatban <i class="fab fa-youtube"></i>](https://www.youtube.com/playlist?list=PLnmeQHnHYqv6ENGrdTXiE9YJrvHuxH2C9){target="_blank"}
    
* **Ajánlott irodalom**
    * Smith, Eliot R., Mackie, Diane M. és Claypool, Heather M. (2016). *Szociálpszichológia.* Budapest, ELTE Eötvös Kiadó. `r emo::ji("flower")` 2. fejezet. Kutatási kérdések felvetése és megválaszolása. 67--104. oldal
    * Carver, Charles S. és Scheier, Michael F. (2011). *Személyiségpszichológia.* Budapest, Osiris Kiadó. `r emo::ji("flower")` 2. fejezet. A személyiségkutatás módszerei. 3. fejezet. A személyiség mérése. 41--71. oldal
    * Atkinson, Richard C., Hilgard, Ernest, Smith, Edward E., Nolen-Hoeksema, Susan, Fredrickson, Barbara L. és Loftus, Geoffrey R. (2005). *Pszichológia.* Budapest, Osiris Kiadó. `r emo::ji("flower")` Kutatási módszerek a pszichológiában. 41--50. oldal. Statisztikai módszerek és mérés. 721--732. oldal
    * Cole, Michael és Cole, Sheila R. (2006). *Fejlődéslélaktan.* Budapest, Osiris Kiadó. `r emo::ji("flower")` A fejlődéslélektan tudománya. 40--56. oldal
    * Freedman, D., Pisani, R., és Roger, P. (2005). *Statisztika - Statisztikai módszerek a társadalomkutatásban.* TYPOTEX, Budapest.
    * Hajtman B. (1968a). *Bevezetés a matematikai statisztikába pszichológusok számára.* Akadémiai Kiadó, Budapest.
    * Hajtman B. (1968b). *Matematikai statisztika pszichológus szakos hallgatók részére.* Akadémiai Kiadó, Budapest.
    * Reiczigel J., Harnos A. és Solymosi N. (2018). *Biostatisztika nem statisztikusoknak.* Pars Kft., Budapest.
    * Vargha A. (1978). *Pszichológiai statisztikai gyakorlat I.* Tankönyvkiadó, Budapest.
    * Vargha A. (1985). *Valószínűségszámítás pszichológus hallgatók számára.* Tankönyvkiadó, Budapest.
    * Vargha A. (1989). *Pszichológiai statisztikai gyakorlat II.* Tankönyvkiadó, Budapest.
    * Vargha A. (2015). *Matematikai statisztika pszichológiai, nyelvészeti és biológiai alkalmazásokkal.* Pólya Kiadó, Budapest.    

